---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-app-run-20241008-001
  namespace: demo-app
  labels:
    app: demo-app
    pipeline: demo-simple-pipeline
spec:
  pipelineRef:
    name: demo-simple-pipeline
  
  params:
    - name: git-url
      value: "https://github.com/waynelw/homelab.git"
    - name: git-revision
      value: "main"
    - name: image-name
      value: "localhost:5000/demo-app:v1.1.0"
  
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  
  timeouts:
    pipeline: "30m"
    tasks: "20m"
