---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-install
  namespace: tekton-pipelines
data:
  install.sh: |
    #!/bin/bash
    # 安装Tekton Pipelines (轻量级版本)
    kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
    
    # 等待部署完成
    kubectl wait --for=condition=ready pod -l app=tekton-pipelines-controller -n tekton-pipelines --timeout=300s
    kubectl wait --for=condition=ready pod -l app=tekton-pipelines-webhook -n tekton-pipelines --timeout=300s
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tekton-installer
  namespace: tekton-pipelines
spec:
  template:
    spec:
      serviceAccountName: tekton-installer
      containers:
      - name: installer
        image: bitnami/kubectl:latest
        command: ["/bin/bash"]
        args: ["/scripts/install.sh"]
        volumeMounts:
        - name: install-script
          mountPath: /scripts
      volumes:
      - name: install-script
        configMap:
          name: tekton-install
          defaultMode: 0755
      restartPolicy: OnFailure
