---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: "5.41.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # 轻量级单实例配置
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false
      
      commonConfig:
        replication_factor: 1
      
      storage:
        type: 'filesystem'
      
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
      
      limits_config:
        retention_period: 168h  # 7天保留期
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20
    
    # 资源限制
    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      
      persistence:
        enabled: true
        size: 5Gi
        storageClass: standard
    
    # 禁用不需要的组件
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    
    # 测试配置
    test:
      enabled: false
    
    # 监控配置
    monitoring:
      serviceMonitor:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
